#include "farversion.hpp"

#define PLUGIN_BUILD 1
#define PLUGIN_DESC L"DlgSelect Plugin for Far Manager"
#define PLUGIN_NAME L"DlgSelect"
#define PLUGIN_FILENAME L"DlgSelect.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
